// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Data {
  meta: Meta;
  data: Datum[];
}

export interface Datum {
  attribution: null;
  tags: string[];
  type: string;
  location: null;
  filter: string;
  created_time: string;
  link: string;
  images: Images;
  users_in_photo: any[];
  caption: Caption;
  user_has_liked: boolean;
  id: string;
  user: User;
  comments?: string[];
}

export interface Caption {
  created_time: string;
  text: string;
  from: User;
  id: string;
}

export interface User {
  username: string;
  profile_picture: string;
  id: string;
  full_name: string;
}

export interface Images {
  low_resolution: LowResolution;
  thumbnail: LowResolution;
  standard_resolution: LowResolution;
}

export interface LowResolution {
  url: string;
  width: number;
  height: number;
}

export interface Meta {
  code: number;
}
